services:
  - type: web
    name: mitch-christiano-bot
    env: docker        
    branch: master
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
